In [13]:
import numpy as np
from sklearn.mixture import GaussianMixture

# Dataset
X = np.array([
    [1], [1.5], [2], [2.5],
    [8], [8.5], [9], [9.5]
])

# Create Gaussian Mixture Model
model = GaussianMixture(
    n_components=2,
    random_state=42
)

# Apply EM algorithm
model.fit(X)

# Predict clusters
labels = model.predict(X)

print("Data:")
print(X.flatten())

print("\nCluster Labels:")
print(labels)

print("\nCluster Means:")
print(model.means_.flatten())

print("\nCluster Probabilities:")
print(model.predict_proba(X))

Data:
[1.  1.5 2.  2.5 8.  8.5 9.  9.5]

Cluster Labels:
[0 0 0 0 1 1 1 1]

Cluster Means:
[1.75 8.75]

Cluster Probabilities:
[[1.00000000e+00 4.52165711e-42]
 [1.00000000e+00 3.30658932e-37]
 [1.00000000e+00 2.41803671e-32]
 [1.00000000e+00 1.76825756e-27]
 [1.76825756e-27 1.00000000e+00]
 [2.41803671e-32 1.00000000e+00]
 [3.30658932e-37 1.00000000e+00]
 [4.52165711e-42 1.00000000e+00]]
